version: "3.8"

services:
  app:
    container_name: image-resizer_app
    build:
      context: .
      dockerfile: .docker/app/dev.Dockerfile
    volumes:
      - ./app/:/app/
      - /app/node_modules
    ports:
      - 8010:8010
    networks:
      - image-resizer
  api:
    container_name: image-resizer_api
    build:
      context: .
      dockerfile: .docker/api/dev.Dockerfile
    ports:
      - 3010:3010
    volumes:
      - ./api:/go/src/github.com/blyndusk/image-resizer/api
    networks:
      - image-resizer

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
      - DATABASE_HOST=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - image-resizer

  adminer:
    image: adminer
    restart: always
    ports:
      - 3011:8080
    depends_on:
      - postgres
    networks:
      - image-resizer

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672

volumes:
  postgres:

networks:
  image-resizer:
