name: DOCKER

on:
  push:
    branches:
      - main

jobs:
  DOCKER-APP:
    name: DOCKER APP
    runs-on: ubuntu-latest
    steps:
      - name: 1 - CHECKOUT
        uses: actions/checkout@v2

      - name: 2 - BUILD + PUSH DOCKER
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: blyndusk/image-resizer_app
          dockerfile: .docker/app/prod.Dockerfile
          tags: "latest"

  DOCKER-API:
    name: DOCKER API
    runs-on: ubuntu-latest
    steps:
      - name: 1 - CHECKOUT
        uses: actions/checkout@v2

      - name: 2 - BUILD + PUSH DOCKER
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: blyndusk/image-resizer_app
          dockerfile: .docker/app/prod.Dockerfile
          tags: "latest"
