name: VUE

on: [push]

jobs:
  INSTALL-LINT-BUILD:
    name: VUE
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: 1 - CHECKOUT
        uses: actions/checkout@v2

      - name: 2 - SETUP NODE 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: 3 - INSTALL DEPENDANCIES
        run: npm install

      - name: 4 - LINT/FORMAT FILES 
        run: npm run lint

      - name: 5 - BUILD APPLICATION
        run: npm run build